### Vscode Extension Rest Client By Huachao Mao

### Create user request

POST http://127.0.0.1:8000/auth/signup
content-type: application/json

{
    "email": "am@am.am",
    "password": "password"
}